## Revision y limpieza dataset

- Leer el dataset
- Analizar las features/descriptores
- Limpieza de tipos de datos
- Evaluar nulos
- Evaluar outliers

In [1]:
import pandas as pd

In [5]:
df_data = pd.read_excel("../raw_data/Basal.xlsx")
df_data

,Unnamed: 0,Unnamed: 1,redcap_repeat_instrument,sex,age,t2m_pre_mean_rr,t2m_pre_rmssd,t2m_pre_sd1,t2m_pre_pns,t2m_pre_mean_hr,...,t2m_pre_lf,t2m_pre_vlf,bp_systolic,bp_diastolic,bp_pam,bp_pp,weight kg,height cm,height mt,imc
0,NaN,NaN,NaN,1.0,75.0,74.8,21.7,274.00,-140.00,80,...,713,172,108,70,82.666667,38,70.0,160,1.60,27.343750
1,NaN,NaN,NaN,1.0,66.0,95.3,18.8,285.00,-54.00,63,...,226,29,122,72,88.666667,50,52.0,149,1.49,23.422368
2,NaN,NaN,NaN,2.0,77.0,87.7,11.7,303.00,-105.00,68,...,137,9,125,85,98.333333,40,81.0,170,1.70,28.027682
3,NaN,NaN,NaN,1.0,77.0,81.9,17.5,376.00,-106.00,73,...,130,14,126,72,90.000000,54,85.0,160,1.60,33.203125
4,NaN,NaN,NaN,1.0,73.0,84.6,13.6,295.00,-115.00,71,...,66,18,130,80,96.666667,50,69.0,151,1.51,30.261831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,NaN,NaN,NaN,2.0,67.0,790.0,16.9,NaN,-1.28,76,...,196,88,134,87,102.666667,47,68.1,154,1.54,28.714792
527,NaN,NaN,NaN,2.0,77.0,814.0,23.8,NaN,-0.98,74,...,261,39,141,80,100.333333,61,67.1,152,1.52,29.042590
528,NaN,NaN,NaN,2.0,61.0,912.0,16.6,NaN,-0.78,66,...,301,27,106,58,74.000000,48,58.4,162,1.62,22.252705
529,NaN,NaN,NaN,2.0,69.0,1016.0,16.9,NaN,-0.25,59,...,189,16,111,72,85.000000,39,80.6,180,1.80,24.876543
530,NaN,NaN,NaN,NaN,NaN,46.8,0.5,5.59,-307.00,46,...,2,1,80,52,66.000000,16,47.0,130,1.30,NaN